config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  root to: "home#index"
  
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope module: 'authors' do 
    resources :posts do 
      resources :elements
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: ['paragraph', 'image', 'video-embed'] }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :elements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors/posts_controller.rb
module Authors 
  class PostsController < AuthorsController
    before_action :set_post, only: [:edit, :update, :destroy]
  
    # GET /posts
    def index
      @posts = current_author.posts
    end
  
    # GET /posts/new
    def new
      @post = current_author.posts.build
    end
  
    # GET /posts/1/edit
    def edit
      @paragraph = @post.elements.build(element_type: 'paragraph')
    end
  
    # POST /posts
    def create
      @post = current_author.posts.build(post_params)
  
      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_post
        @post = current_author.posts.find(params[:id])
      end
  
      # Only allow a trusted parameter "white list" through.
      def post_params
        params.require(:post).permit(:title, :description)
      end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_author!

    layout 'authors'
end

app/controllers/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: [:update, :destroy]
  
    # POST /elements
    def create
      @element = @post.elements.build(element_params)
  
      if @element.save
        notice = nil
      else
        notice = @element.errors.full_messages.join(". ") << "."
      end
      redirect_to edit_post_path(@post), notice: notice
    end
  
    # PATCH/PUT /elements/1
    def update
      if @element.update(element_params)
        redirect_to @element, notice: 'Element was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to elements_url, notice: 'Element was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.

      def set_post
        @post = current_author.posts.find(params[:post_id])
      end

      def set_element
        @element = @post.element.find(params[:id])
      end
  
      # Only allow a trusted parameter "white list" through.
      def element_params
        params.require(:element).permit(:element_type, :content)
      end
  end  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .actions = f.submit class: 'btn btn-primary'

app/views/authors/posts/edit.html.slim
.row
    .col-md-3
        = link_to 'Back', posts_path, class: 'btn btn-secondary mb-3'
        .card.p-4
            h4 Editing Post
            = render 'form', post: @post
    .col-md-9
        = form_with(model: [@post, @paragraph]) do |form|
            = form.hidden_field :element_type, value: 'paragraph'
            = form.submit "Paragraph", class: 'btn btn-primary'
        - @post.elements.each do |element|
            = form_with(model: [@post, element]) do |form|
                = form.text_area :content
                = form.submit "Save", class: 'btn btn-primary'

        

app/views/authors/posts/index.html.slim
h4.d-flex.justify-content-between
  span Listing posts
  = link_to 'New Post', new_post_path, class: 'btn btn-primary'


- @posts.each do |post|
  = link_to edit_post_path(post), class: 'text-decoration-none' do
    .card.mb-3
      .card-body
        h5.card-title.text-dark.mb-1 = post.title
        p.text-secondary.mb-0 = post.description
      

app/views/authors/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/authors.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <div class="containter">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
    </div>
  </body>
</html>
 